#!/bin/bash

# ----------------------------------------------------------------------
# | Navigation                                                         |
# ----------------------------------------------------------------------

alias ~="cd ~" # `cd` is probably faster to type though
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias cd..="cd .."
alias -- -="cd -"

# ----------------------------------------------------------------------
# | Network                                                            |
# ----------------------------------------------------------------------

alias ip="dig +short myip.opendns.com @resolver1.opendns.com"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if [ "$OS" == "osx" ]; then
    alias local-ip="ipconfig getifaddr en1"
elif [ "$OS" == "ubuntu" ]; then
    alias local-ip="ifconfig | \
                   grep 'inet addr' | \
                   grep -v '127.0.0.1' | \
                   cut -d: -f2 | \
                   cut -d' ' -f1"
fi

# ----------------------------------------------------------------------
# | Package Managers                                                   |
# ----------------------------------------------------------------------

# npm
# https://docs.npmjs.com/

if [ -x "$(command -v npm)" ]; then
    alias npmi="npm install"
    alias npmr="npm uninstall"
    alias npms="npm search"
    alias npmu="npm update"
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# OS specific package managers

if [ "$OS" == "osx" ]; then

    # Homebrew
    # http://brew.sh/

    if [ -x "$(command -v brew)" ]; then
        alias brewd="brew doctor"
        alias brewi="brew install"
        alias brewr="brew uninstall"
        alias brews="brew search"
        alias brewu="brew update &&  \
                     brew upgrade && \
                     brew cleanup"
    fi

elif [ "$OS" == "ubuntu" ]; then

    # Advanced Packaging Tool

    alias apti="sudo apt-get install"
    alias aptr="sudo apt-get remove"
    alias apts="sudo apt-cache search"
    alias aptu="sudo apt-get update && \
                sudo apt-get upgrade"
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Update

if [ "$OS" == "osx" ]; then
    alias update="sudo softwareupdate --install --all && \
                  brewu && \
                  npmi -g npm && \
                  npmu -g"
elif [ "$OS" == "ubuntu" ]; then
    alias update="aptu && \
                  npmi -g npm && \
                  npmu -g"
fi

# ----------------------------------------------------------------------
# | Shorter Commands                                                   |
# ----------------------------------------------------------------------

alias :q="exit"
alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias e="vim"
alias g="git"
alias ll="ls -l"
alias m="man"
alias map="xargs -n1"
alias q="exit"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Copy to clipboard

if [ "$OS" == "osx" ]; then
    alias cc="pbcopy"
elif [ "$OS" == "ubuntu" ]; then
    alias cc="xclip -selection clip"
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Empty Trash

if [ "$OS" == "osx" ]; then

    # Empty the trash, the main HDD and on all mounted volumes
    # and clear Apple’s system logs to improve shell startup speed

    alias empty-trash="sudo rm -frv /Volumes/*/.Trashes && \
                      sudo rm -frv ~/.Trash &&
                      sudo rm -frv /private/var/log/asl/*.asl"
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Hide/Show files

if [ "$OS" == "osx" ]; then

    # Hide/Show desktop icons
    alias hide-desktop-icons="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
    alias show-desktop-icons="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

    # Hide/Show hidden files in Finder
    alias hide-hidden-files="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"
    alias show-hidden-files="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"

elif [ "$OS" == "ubuntu" ]; then

    # Hide/Show desktop icons
    alias hide-desktop-icons="gsettings set org.gnome.desktop.background show-desktop-icons false"
    alias show-desktop-icons="gsettings set org.gnome.desktop.background show-desktop-icons true"

fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Lock screen

if [ "$OS" == "osx" ]; then
    alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Open

if [ "$OS" == "osx" ]; then
    alias o="open"
elif [ "$OS" == "ubuntu" ]; then
    alias o="xdg-open"
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if [ "$OS" == "osx" ]; then
    alias use-node="brew unlink iojs && brew link --force node"
    alias use-iojs="brew unlink node && brew link --force iojs"
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# From my mac
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Shortcuts
alias cdd="cd ~/Documents"
alias dl="cd ~/Downloads"
alias cdb="cd ~/Desktop"
alias cdp="cd ~/projects"
alias g="git"
alias h="history"
alias j="jobs"

# programs
# TODO: ubuntu version
if [ "$OS" == "osx" ]; then
  alias st='open -a "Sublime Text 3"'
  # also/or do this:
  # ln -s "/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl" ~/bin/subl
  alias preview="open -a '$PREVIEW'"
  alias xcode="open -a '/Developer/Applications/Xcode.app'"
  alias filemerge="open -a '/Developer/Applications/Utilities/FileMerge.app'"
  alias safari="open -a safari"
  alias firefox="open -a firefox"
  alias opera="open -a opera"
  alias chrome="open -a google\ chrome"
  alias chromium="open -a chromium"
  alias dashcode="open -a dashcode"
  alias finder='open -a Finder'
  alias fireworks="open -a '/Applications/Adobe Fireworks CS6/Adobe Fireworks CS6.app'"
  alias photoshop="open -a '/Applications/Adobe Photoshop CS6/Adobe Photoshop.app'"
  #alias gpr="~/utils/gpr $1"
  alias gh="open -a google\ chrome 'http://github.com/bmedy'"
fi

# general shortcuts
alias pro="cd ~/projects"
#alias bl="open -a google\ chrome 'http://browserling.com'"

# be nice
alias please=sudo

# List all files colorized in long format
alias l="ls -l"

# List all files colorized in long format, including dot files
alias la="ls -la"
alias ll="ls -la"

# List only directories
alias lsd='ls -l | grep "^d"'

# Stopwatch
alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'

# `cat` with beautiful colors. requires Pygments installed.
#                  sudo easy_install Pygments
alias c='pygmentize -O style=monokai -f console256 -g'

# Shortcuts
alias g="git"
alias v="vim"

# File size
alias fs="stat -f \"%z bytes\""

